import type { Metadata } from 'next';
import { inter, poppins } from '@/config/fonts';
import './globals.css';
import SWRProvider from '@/providers/swr-provider';
import { Toaster } from '@/components/ui/sonner';
import CsrfProvider from '@/providers/csrf-provider';

export const metadata: Metadata = {
  title: 'FloodWatch',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, interactive-widget=resizes-content'
        />
      </head>
      <body
        className={`${inter.className} ${poppins.variable} bg-[#EAEAEA] antialiased min-h-screen`}
        suppressHydrationWarning
      >
        <SWRProvider fallback={{}}>
          <CsrfProvider>{children}</CsrfProvider>
        </SWRProvider>
        <Toaster richColors theme='light' position='top-center' />
      </body>
    </html>
  );
}
