import type { Metadata } from 'next';
import { inter, poppins } from '@/config/fonts';
import './globals.css';
import SWRProvider from '@/providers/swr-provider';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'FloodWatch',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable} bg-[#EAEAEA] antialiased min-h-screen`}
      >
        <SWRProvider fallback={{}}>{children}</SWRProvider>
        <Toaster richColors theme="light" position="top-center" />
      </body>
    </html>
  );
}
